### PR TITLE
fix(wrap): Extensions `functions.handler` -> `eventType` key exists but is `undefined` value

### PR DESCRIPTION
**Pull request by Salakar**
### Description

I've been working on adding tests to [firebase/extensions](https://github.com/firebase/extensions) and when trying to wrap the function handlers used by Extensions (e.g. `functions.handler.firestore.document.onWrite`) it errors with `TypeError: Cannot read property 'match' of undefined` as the `eventType` key 'does' exist on the `defaultContext` object, but has an `undefined` value assigned.

This small PR adds an additional `undefined` check.

```js
export const fstranslate = functions.handler.firestore.document.onWrite(
  async (change): Promise<void> => {
  console.warn('Hello from inside my wrapped handler function.');
  return;
});

// ...
import * as functionsTestInit from "firebase-functions-test";
// ...
let functionsTest = functionsTestInit();
// ...


const wrappedFn = functionsTest.wrap(exportedFns.fstranslate);
const before = functionsTest.firestore.makeDocumentSnapshot({}, "foo/id1");
const after = functionsTest.firestore.makeDocumentSnapshot({ input: "hello" }, "foo/id1");
const change = functionsTest.makeChange(before, after);

wrappedFn(change); // Errors
```

**Before**:
image

**After**:
image

### Code sample

N/A

----

cc @laurenzlong @karayu

### CODE REVIEW

**Comment by Salakar** [comment]
> Thanks for the fix! there seems to be some TS errors

These are on master too - but I'll look into it, thanks!

**Comment by Salakar** [comment]
@laurenzlong fixed the types issue that was on master - breaking change in the `chai` types that was non semver, I've switched the version in `package.json` to use approximate versioning.

Came across another issue with the dev dependencies where the `firebase-admin` SDK was quite far out of date that the native GRPC dep wouldn't compile on the latest stable Node.js version - so I updated  to the latest `firebase-admin` & `firebase-functions` versions. This broke the types as `typescript` was too old, updated typescript to fix, that broke mocha types as too old, and so on 😅 - so I've just updated all of the dev dependencies and all is working well now.

I also had to remove Node.js v6 testing from travis - newer `firebase-functions` versions uses async/await which isn't available on v6. Also the `functions` runtimes now are only v8 & v10 so have updated travis to reflect.

Hope these additional changes to get CI working again are ok?

**Comment by laurenzlong** [comment]
@Salakar This has now been released in v0.1.7

**Comment by Salakar** [comment]
@laurenzlong Thank you 🎉

**Pull request merged**
